### ISSUE TITLE
Sending a player connected to the webapp

### ISSUE THREAD

**Issue by LeonardGr** [PYM-Team/API#26]
Script de connection d'un joueur sur mobile envoi 10 fois le rôle.
Côté Webapp - renvoi 10 update Player

**Comment by LeonardGr** [comment]
![image](https://user-images.githubusercontent.com/48238257/82468489-23508080-9ac3-11ea-81d6-5bec29e09f10.png)
Renvoi aussi des noms de joueurs inconnus

**Comment by wo0lien** [comment]
Je n'arrive plus a reproduire le problème alors ca devrait être réglé
